### ISSUE TITLE
skse64.patch doesn't apply cleanly to skse64_2_00_17.7z

### ISSUE THREAD

**Issue by pcbeard** [SlavicPotato/sse-build-resources#1]
I get these errors when I try to follow your instructions:

Downloaded 2.0.17 from here:

http://skse.silverlock.org/download/archive/skse64_2_00_17.7z

git apply produces:

error: patch failed: skse64/skse64/NiProperties.h:197
error: skse64/skse64/NiProperties.h: patch does not apply
error: patch failed: skse64/skse64/NiTextures.cpp:1
error: skse64/skse64/NiTextures.cpp: patch does not apply
error: patch failed: skse64/skse64/NiTextures.h:198
error: skse64/skse64/NiTextures.h: patch does not apply
error: patch failed: skse64/skse64/ObScript.cpp:2
error: skse64/skse64/ObScript.cpp: patch does not apply
error: patch failed: skse64/skse64_common/Utilities.cpp:252
error: skse64/skse64_common/Utilities.cpp: patch does not apply

I noticed the patch file was encoded in UTF-16 initially. I had to reencode as UTF-8 to be able to use `git apply` using WSL. Am I doing something wrong?

**Comment by SlavicPotato** [comment]
Not your fault, the patch was borked. The current one should be fine.

**Comment by pcbeard** [comment]
Thanks!

**Comment by SlavicPotato** [comment]
The new patch was pushed five days ago.
