### ISSUE TITLE
build with Windows 10 SDK?

### ISSUE THREAD

**Issue by pcbeard** [SlavicPotato/sse-build-resources#2]
I tried to retarget all projects to use Windows 10 SDK to build and I'm close, but the build fails with this error using VS 2019 CE:

1>------ Build started: Project: sse-build-resources, Configuration: Debug x64 ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(408,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32.
1>Done building project "common_vc14.vcxproj" -- FAILED.
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(408,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Debug|Win32.
1>Done building project "skse64_common.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by SlavicPotato** [comment]
Most configs are already setup to use at the latest installed version. Some are stale however, Release MT, ReleaseAVX2 MT, DEP-AVX(2) and DEP-SSE are fine, they're used by SDT and CBP solutions.
